# Generated by Django 5.2.17 on 2026-09-24 00:29

import apps.sync.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MdblistAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdblist_username', models.CharField(blank=True, max_length=255)),
                ('mdblist_user_id', models.CharField(blank=True, max_length=32)),
                ('plan', models.CharField(blank=True, max_length=32)),
                ('is_supporter', models.BooleanField(default=False)),
                ('auth_method', models.CharField(choices=[('oauth', 'OAuth'), ('apikey', 'API key')], default='oauth', max_length=8)),
                ('access_token', apps.sync.fields.EncryptedTextField(default='')),
                ('refresh_token', apps.sync.fields.EncryptedTextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('initial_sync_complete', models.BooleanField(default=False)),
                ('activities_cursor', models.CharField(blank=True, max_length=40)),
                ('last_activities', models.JSONField(blank=True, default=dict)),
                ('pending_pushes', models.JSONField(blank=True, default=dict)),
                ('sync_status', models.CharField(choices=[('ok', 'OK'), ('error', 'Error'), ('reauthorize', 'Reauthorize')], default='ok', max_length=16)),
                ('last_error', models.TextField(blank=True)),
                ('last_warning', models.TextField(blank=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mdblist_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MdblistLibraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('show', 'Show')], max_length=8)),
                ('tmdb_id', models.PositiveBigIntegerField()),
                ('ids', models.JSONField(blank=True, default=dict)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('watched_at', models.DateTimeField(blank=True, null=True)),
                ('on_watchlist', models.BooleanField(default=False)),
                ('dropped', models.BooleanField(default=False)),
                ('user_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('watched_episodes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_items', to='mdblist.mdblistaccount')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('account', 'media_type', 'tmdb_id'), name='mdblist_library_item_account_media_uniq')],
            },
        ),
        migrations.CreateModel(
            name='MdblistMediaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('media_type', models.CharField(blank=True, max_length=8)),
                ('mdblist_id', models.CharField(blank=True, max_length=32)),
                ('slug', models.CharField(blank=True, max_length=255)),
                ('imdb_id', models.CharField(blank=True, max_length=32)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ratings', models.JSONField(blank=True, default=list)),
                ('certification', models.CharField(blank=True, max_length=32)),
                ('trailer_url', models.CharField(blank=True, max_length=255)),
                ('streams', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('not_found', 'Not found'), ('error', 'Error')], default='ok', max_length=16)),
                ('last_error', models.TextField(blank=True)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mdblist_media_info', to='contenttypes.contenttype')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id'), name='mdblist_media_info_content_uniq')],
            },
        ),
        migrations.CreateModel(
            name='MdblistSyncIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('movie_watchlist', 'Movie watchlist'), ('show_watchlist', 'Show watchlist'), ('movie_history', 'Movie history'), ('episode_history', 'Episode history'), ('show_dropped', 'Dropped show'), ('movie_rating', 'Movie rating'), ('show_rating', 'Show rating')], max_length=32)),
                ('identity_key', models.CharField(max_length=512)),
                ('payload', models.JSONField(default=dict)),
                ('desired', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mdblist_sync_intents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('kind', 'identity_key'),
                'constraints': [models.UniqueConstraint(fields=('user', 'kind', 'identity_key'), name='mdblist_intent_user_kind_identity_uniq')],
            },
        ),
    ]
