# Generated by Django 5.2.15 on 2026-07-05 01:03

import apps.users.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.users.managers.UserManager()),
            ],
        ),
    ]
