# Generated by Django 5.2.15 on 2026-07-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="tmdb_metadata_language",
            field=models.CharField(
                default="en-US",
                max_length=16,
                verbose_name="Movie metadata language",
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="tvdb_metadata_language",
            field=models.CharField(
                default="eng",
                max_length=16,
                verbose_name="TV metadata language",
            ),
        ),
    ]
