# Generated by Django 5.2.15 on 2026-07-20 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trakt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traktaccount',
            name='episode_history_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TraktWatchedEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_key', models.CharField(max_length=512)),
                ('show_data', models.JSONField(default=dict)),
                ('episode_data', models.JSONField(default=dict)),
                ('season_number', models.PositiveIntegerField()),
                ('episode_number', models.PositiveIntegerField()),
                ('watched_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_episode_cache', to='trakt.traktaccount')),
            ],
            options={
                'indexes': [models.Index(fields=['account', 'watched_at'], name='trakt_trakt_account_7434c8_idx')],
                'constraints': [models.UniqueConstraint(fields=('account', 'identity_key'), name='trakt_watched_episode_account_identity_uniq')],
            },
        ),
    ]
