# Generated by Django 5.2.15 on 2026-09-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trakt', '0002_traktaccount_episode_history_synced_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traktaccount',
            name='redirect_uri',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
