# Generated by Django 5.1.7 on 2026-08-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imports", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="importjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ("queued", "processing"))),
                fields=("user", "service"),
                name="imports_active_user_service_uniq",
            ),
        ),
    ]
