# Generated by Django 5.2.15 on 2026-08-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_importjob_active_user_service_uniq'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='ratings_applied',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
