# Generated by Django 5.2.15 on 2026-07-13 18:30

from django.db import migrations, models


def seed_movie_translations(apps, schema_editor):
    Movie = apps.get_model("movies", "Movie")
    for movie in Movie.objects.iterator():
        values = {
            key: value
            for key, value in {
                "title": movie.title,
                "overview": movie.overview,
                "tagline": movie.tagline,
            }.items()
            if value
        }
        if not values:
            continue
        movie.translations = {"en-US": values}
        movie.save(update_fields=["translations"])


def preserve_scalar_fallbacks(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_cast_director_trailer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(seed_movie_translations, preserve_scalar_fallbacks),
    ]
