# Generated by Django 5.2.17 on 2026-08-25 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_movie_original_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermovie',
            name='tier',
        ),
    ]
