# Generated by Django 5.2.15 on 2026-07-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=16)),
                ('external_id', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_id'), name='catalog_genre_provider_external_id_uniq')],
            },
        ),
    ]
