# Generated by Django 5.2.15 on 2026-07-13 18:30

from django.db import migrations, models


def seed_genre_translations(apps, schema_editor):
    Genre = apps.get_model("catalog", "Genre")
    for genre in Genre.objects.iterator():
        if not genre.name:
            continue
        language = "en-US" if genre.provider == "tmdb" else "eng"
        genre.translations = {language: {"name": genre.name}}
        genre.save(update_fields=["translations"])


def preserve_scalar_fallbacks(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(seed_genre_translations, preserve_scalar_fallbacks),
    ]
