// Lucide icon rendering. Templates declare icons with <i data-lucide="icon-name">;
// this replaces them with inline SVGs at runtime.
import {
    ArrowRightLeft,
    Bookmark,
    Calendar,
    CalendarClock,
    CalendarDays,
    CalendarX,
    Check,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronsLeft,
    ChevronsRight,
    CircleAlert,
    CircleCheck,
    CircleMinus,
    CirclePlay,
    CircleQuestionMark,
    Clapperboard,
    Clock,
    Copy,
    Database,
    DoorOpen,
    Ellipsis,
    ExternalLink,
    Eye,
    EyeOff,
    FastForward,
    FileInput,
    FileUp,
    Film,
    Flag,
    GalleryHorizontalEnd,
    House,
    Image,
    Info,
    Link,
    ListOrdered,
    Menu,
    Moon,
    Pause,
    Play,
    RadioTower,
    RefreshCw,
    RotateCcwClock,
    Search,
    Settings,
    Share,
    ShieldHalf,
    SkipForward,
    SlidersHorizontal,
    SquarePen,
    Star,
    Sun,
    Trash2,
    TriangleAlert,
    Tv,
    Unlink,
    User,
    Users,
    WandSparkles,
    Wrench,
    X,
} from 'lucide';
import { createIcons } from 'lucide';

const icons = {
    ArrowRightLeft,
    Bookmark,
    Calendar,
    CalendarClock,
    CalendarDays,
    CalendarX,
    Check,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronsLeft,
    ChevronsRight,
    CircleAlert,
    CircleCheck,
    CircleMinus,
    CirclePlay,
    CircleQuestionMark,
    Clapperboard,
    Clock,
    Copy,
    Database,
    DoorOpen,
    Ellipsis,
    ExternalLink,
    Eye,
    EyeOff,
    FastForward,
    FileInput,
    FileUp,
    Film,
    Flag,
    GalleryHorizontalEnd,
    House,
    Image,
    Info,
    Link,
    ListOrdered,
    Menu,
    Moon,
    Pause,
    Play,
    RadioTower,
    RefreshCw,
    RotateCcwClock,
    Search,
    Settings,
    Share,
    ShieldHalf,
    SkipForward,
    SlidersHorizontal,
    SquarePen,
    Star,
    Sun,
    Trash2,
    TriangleAlert,
    Tv,
    Unlink,
    User,
    Users,
    WandSparkles,
    Wrench,
    X,
};

export function renderIcons() {
    createIcons({ icons });
}

renderIcons();

// HTMX swaps inject new placeholders; re-render after they settle.
document.addEventListener('htmx:afterSettle', () => {
    renderIcons();
});
