# Generated by Django 5.2.17 on 2026-08-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stremio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stremioaccount',
            name='deferred_content_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='stremioaccount',
            name='last_warning',
            field=models.TextField(blank=True),
        ),
    ]
