# Generated by Django 5.2.15 on 2026-09-18 01:32

import apps.trakt.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimklAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simkl_username', models.CharField(blank=True, max_length=255)),
                ('simkl_user_id', models.CharField(blank=True, max_length=32)),
                ('account_type', models.CharField(blank=True, max_length=16)),
                ('access_token', apps.trakt.fields.EncryptedTextField(default='')),
                ('initial_sync_complete', models.BooleanField(default=False)),
                ('activities_cursor', models.CharField(blank=True, max_length=40)),
                ('last_activities', models.JSONField(blank=True, default=dict)),
                ('pending_pushes', models.JSONField(blank=True, default=dict)),
                ('sync_status', models.CharField(choices=[('ok', 'OK'), ('error', 'Error'), ('reauthorize', 'Reauthorize')], default='ok', max_length=16)),
                ('last_error', models.TextField(blank=True)),
                ('last_warning', models.TextField(blank=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='simkl_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SimklLibraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('show', 'Show'), ('anime', 'Anime')], max_length=8)),
                ('simkl_id', models.PositiveBigIntegerField()),
                ('ids', models.JSONField(blank=True, default=dict)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=16)),
                ('last_watched_at', models.DateTimeField(blank=True, null=True)),
                ('user_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('watched_episodes', models.JSONField(blank=True, default=dict)),
                ('watched_episodes_count', models.PositiveIntegerField(default=0)),
                ('total_episodes_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_items', to='simkl.simklaccount')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('account', 'media_type', 'simkl_id'), name='simkl_library_item_account_media_uniq')],
            },
        ),
        migrations.CreateModel(
            name='SimklMediaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('media_type', models.CharField(blank=True, max_length=8)),
                ('simkl_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('slug', models.CharField(blank=True, max_length=255)),
                ('simkl_rating', models.FloatField(blank=True, null=True)),
                ('simkl_votes', models.PositiveIntegerField(blank=True, null=True)),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
                ('imdb_votes', models.PositiveIntegerField(blank=True, null=True)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('drop_rate', models.CharField(blank=True, max_length=16)),
                ('certification', models.CharField(blank=True, max_length=32)),
                ('trailer_url', models.CharField(blank=True, max_length=255)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('not_found', 'Not found'), ('error', 'Error')], default='ok', max_length=16)),
                ('last_error', models.TextField(blank=True)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simkl_media_info', to='contenttypes.contenttype')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id'), name='simkl_media_info_content_uniq')],
            },
        ),
        migrations.CreateModel(
            name='SimklSyncIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('movie_watchlist', 'Movie watchlist'), ('show_watchlist', 'Show watchlist'), ('movie_history', 'Movie history'), ('episode_history', 'Episode history'), ('show_dropped', 'Dropped show'), ('show_paused', 'Paused show'), ('movie_rating', 'Movie rating'), ('show_rating', 'Show rating')], max_length=32)),
                ('identity_key', models.CharField(max_length=512)),
                ('payload', models.JSONField(default=dict)),
                ('desired', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simkl_sync_intents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('kind', 'identity_key'),
                'constraints': [models.UniqueConstraint(fields=('user', 'kind', 'identity_key'), name='simkl_intent_user_kind_identity_uniq')],
            },
        ),
    ]
