# Generated by Django 5.2.15 on 2026-09-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simkl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simklaccount',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
