# Generated by Django 5.2.15 on 2026-07-05 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='airs_schedule',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='show',
            name='average_runtime',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='cast',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='show',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='last_air_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='next_air_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='trailer_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
