# Generated by Django 5.2.15 on 2026-07-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0002_show_cast_trailer_imdb_air_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='finale_type',
            field=models.CharField(blank=True, choices=[('season', 'Season'), ('midseason', 'Midseason'), ('series', 'Series')], max_length=16, null=True),
        ),
    ]
