# Generated by Django 5.2.15 on 2026-07-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tv", "0003_episode_finale_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="tmdb_id",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
