# Generated by Django 5.2.15 on 2026-07-11 00:01

from django.db import migrations, models


def populate_status(apps, schema_editor):
    UserShow = apps.get_model("tv", "UserShow")
    UserShow.objects.filter(is_tracking=True).update(status="tracked")
    UserShow.objects.filter(is_tracking=False).update(status="dropped")


def restore_tracking(apps, schema_editor):
    UserShow = apps.get_model("tv", "UserShow")
    UserShow.objects.filter(status="tracked").update(is_tracking=True)
    UserShow.objects.exclude(status="tracked").update(is_tracking=False)


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0004_show_tmdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name="usershow",
            name="status",
            field=models.CharField(
                choices=[("tracked", "Tracked"), ("paused", "Paused"), ("dropped", "Dropped")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.RunPython(populate_status, restore_tracking),
        migrations.RemoveField(
            model_name="usershow",
            name="is_tracking",
        ),
        migrations.AlterField(
            model_name="usershow",
            name="status",
            field=models.CharField(
                choices=[("tracked", "Tracked"), ("paused", "Paused"), ("dropped", "Dropped")],
                default="tracked",
                max_length=8,
            ),
        ),
    ]
