# Generated by Django 5.2.15 on 2026-07-13 18:30

from django.db import migrations, models


def _seed_translations(model, fields):
    for item in model.objects.iterator():
        values = {
            field: getattr(item, field)
            for field in fields
            if getattr(item, field)
        }
        if not values:
            continue
        item.translations = {"eng": values}
        item.save(update_fields=["translations"])


def seed_tv_translations(apps, schema_editor):
    _seed_translations(apps.get_model("tv", "Show"), ("name", "overview"))
    _seed_translations(apps.get_model("tv", "Season"), ("name", "overview"))
    _seed_translations(apps.get_model("tv", "Episode"), ("name", "overview"))


def preserve_scalar_fallbacks(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("tv", "0006_remove_show_airs_schedule_show_airs_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="translations",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="season",
            name="translations",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="show",
            name="translations",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(seed_tv_translations, preserve_scalar_fallbacks),
    ]
