# Generated by Django 5.2.17 on 2026-08-25 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0015_show_original_title_and_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usershow',
            name='tier',
        ),
    ]
